name: codio-publish
on:
  push:
    branches:
      - names

jobs:

  publish: 
    runs-on: ubuntu-20.04
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Cleanup
        run: rm -rf README.md
      
      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@d7249b1cd44783dab28f02c8479802e74a1307d9
        
        with:
          client-id: ${{ secrets.CODIO_DEMO_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_DEMO_SECRET_ID }}
          # course-id: 1a6dd23261de591822b3073056935856
          # assignment-id: 0728352b03fe5d50fdaeb91898d54a17
          course-name: github actions
          assignment-name: assignment1
          dir: ./
          # yml: .guides/yaml_map
          changelog: ${{ github.event.head_commit.message }}
          domain: test2-codio.com
