name: codio-publish
on:
  push:
    branches:
      - names

jobs:

  publish: 
    runs-on: ubuntu-20.04
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Cleanup
        run: rm -rf README.md
      
      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@6cea9b418aaa120d63f3ac3974f9a5015ff001d7
        
        with:
          client-id: ${{ secrets.CODIO_DEMO_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_DEMO_SECRET_ID }}
          # course-id: 1a6dd23261de591822b3073056935856
          # assignment-id: 0728352b03fe5d50fdaeb91898d54a17
          course-name: Github actions
          assignment-name: аssignment4
          # course-name: русский
          # assignment-name: ассаймент 1
          dir: ./
          # yml: .guides/yaml_map
          changelog: ${{ github.event.head_commit.message }}
          domain: test2-codio.com
